school/config/routes.rb
Rails.application.routes.draw do
  get 'faculties/show'
  get 'faculties/:id' => 'faculties#show'

  get 'courses/show'
  get 'courses/:id' => 'courses#datail'

  resources :students
  resources :faculties, only: [ :show ]
  resources :courses, only: [ :show, :datail ]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

school/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

school/app/models/course.rb
class Course < ApplicationRecord
end

school/app/models/faculty.rb
class Faculty < ApplicationRecord
    has_many :students
end

school/app/models/student.rb
class Student < ApplicationRecord
  belongs_to :faculty
end

school/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

school/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def show
    @course = Course.all
  end

  def datail
    @datail = Course.find(params[:id])
  end
end

school/app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  def show
    # url paramで学部を指定
    @faculty = Faculty.find(params[:id])
    @students = @faculty.students
  end
end

school/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :faculty_id, :grade)
    end
end

school/app/helpers/application_helper.rb
module ApplicationHelper
end

school/app/helpers/courses_helper.rb
module CoursesHelper
end

school/app/helpers/faculties_helper.rb
module FacultiesHelper
end

school/app/helpers/students_helper.rb
module StudentsHelper
end

school/app/views/courses/datail.html.erb
<h2><%= @datail.name %></h2>
<table>
  <thead>
    <tr>
      <th>id</th>
      <th>name</th>
      <th>credit</th>
      <th>compulsory</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @datail.id %></td>
        <td><%= @datail.name %></td>
        <td><%= @datail.credit %></td>
        <td><%= @datail.compulsory %></td>
      </tr>
  </tbody>
</table>

school/app/views/courses/show.html.erb
<h2>courses</h2>
<table>
  <thead>
    <tr>
      <th>id</th>
      <th>name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @course.each do |c| %>
      <tr>
        <td><%= c.id %></td>
        <td><%= c.name %></td>
        <td><a href="<%= c.id %>">jump</a></td>
      </tr>
    <% end %>
  </tbody>
</table>

school/app/views/faculties/show.html.erb
<h1>Faculties#show</h1>
<p><b><%= @faculty.name %></b></p>

school/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>School</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= image_tag "http://www.sfc.keio.ac.jp/img/logo.png" %>
  </body>
</html>

school/app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :faculty_id %>
    <%= form.collection_select :faculty_id, Faculty.all, :id, :name %>
  </div>

    <div class="field">
    <% (1..4).each do |g| %>
        <%= form.radio_button :grade, g %>
        <%= form.label :grade, g.to_s + '年', value: g %>
        <span> / </span>
    <% end %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

school/app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

school/app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Faculty</th>
      <th>Grade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.faculty.name %></td>
        <td><%= student.grade %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

school/app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

school/app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Faculty:</strong>
  <%= @student.faculty_id %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>